# Mains {-}

## Chicken

### Honey-sriracha wings

**Ingredients**

*Wings*

-  1 kg chicken wings split at the joints with tips removed
-  2 tbsp melted unsalted butter
-  1 tsp garlic
-  Salt and pepper for seasoning
-  Cumin and turmeric
-  Vegetable oil

*Sauce*

-  5 tbsp unsalted butter
-  1/3 cup honey + more for drizzling
-  0.25 cup sriracha (thai chilli sauce)
-  1 tbsp soy Sauce
-  2 tsp lime juice

**Method**

1.  Marinate the ingredients for the *wings* together and leave for a while (longer the better).
2.  Preheat oven to 200°C.
3.  Bake the wings until browned and crisp (45 to 55 minutes).
4.  Mix the ingredients for the *sauce* together. Dip the wings in the *sauce* and serve.

### Mum's turmeric Chicken

**Ingredients**

-  1 tsp turmeric (? add more wtf??)
-  4 kg Chicken
-  2 tbsp coriander
-  2 tsp fennel
-  2 tsp cumin (ditto)
-  2 tbsp salt
-  12 tbsp sugar
-  2 tbsp blended lemon grass
-  4 tbsp blended onion
-  2 tsp blended garlic

**Method**

1.  Marinate the chicken with everything. After 10 minutes add oil and refrigerate overnight.
2.  Fry.

*Protip*: cook it at some outdoor barbecues which are hot and fast.

## Pork

### Aunty Sonia's red vinegar pork spare ribs

**Ingredients**

-  2 tbsp red vinegar (can use black vinegar)
-  4 tbsp chinese wine
-  1 block rock sugar
-  6 tbsp soy sauce (light)
-  1 rack of pork spare ribs

**Method**

1.  On low heat boil everything together.
2.  Cover and simmer for $1\frac{1}{2}$ hours.
3.  If too thick add water.

### Bak kua

**Ingredients**

-  300 g lean pork mince
-  300 g bun fei san mince
-  135 g sugar
-  3 tbsp fish sauce
-  1 tsp soy sauce
-  0.25 tsp salt
-  0.25 tsp pepper
-  1 tsp wine

**Method**

1.  Mix everything together then roll out into a thin strip.
2.  Dry it outside under the sun.
3.  Cut it up then fry.

### Bak kut teh

<add stuff>

## Duck

## Lor ark (teochew duck)

\textbf{Ingredients}

-  Duck
    -  1 whole large duck
    -  3 tbsp sea salt
    -  1 tbsp five spice powder
    -  2 tbsp superior black soya sauce
-  Braising sauce
    -  40 g white sugar
    -  100g galangal (cut into thick slices)
    -  $\frac{1}{2}$ tsp five spice powder
    -  2 cinnamon sticks
    -  2 star anises
    -  4 cloves
    -  5 cloves of garlic
    -  1-1.5 cups superior dark soya sauce
    -  1 cup superior light soya sauce
    -  Water (sufficient to slightly cover the duck)
    -  Salt/sugar (optional)
-  Garlic Chilli Vinegar Dipping Sauce (never tried)
    -  7 cloves garlic (chopped finely then pound)
    -  2 bird eyes chillies (chopped finely then pound)
    -  10 tbsp of white vinegar
-  Additional
    -  Hardboiled eggs
    -  Firm bean curd
    -  4 Bean curd puff

**Method**

1.  Rub salt over the whole duck and let it marinate for half an hour or more to get rid of some of its odour.
2.  Wash off salt and also wax from the under wing and thighs of the duck and remove any feathers.
3.  Drain well.
4.  Rub the black soya sauce and five spice powder all over the duck including the cavity and let it marinate for an hour.
5.  Heat up wok and add sugar till caramelized.
6.  Transfer duck and coat the breast side first with the caramelized sugar and then turn to the other side and repeat till the whole duck is nicely coated with the sugar.
7.  Then turn back the duck, breast side down.
8.  Next, add the rest of the ingredients.
9.  Add in any of the optional ingredients at this point.
10.  Bring to boil and lower to medium heat, cover and let it braise for an hour. Turn the duck every 30 minutes.
11.  Turn the duck again and braise for another 10 minutes. The meat is usually cooked by now and the meat is firm. If you prefer the meat to be softer, braise for another 10 minutes.
12.  Dipping sauce: combine all ingredients and mix well.
13.  Once the duck is cooked, let it rest for at least an hour or more in the gravy.
14.  Then take it out from the gravy and drain before cutting it into pieces. Transfer them on a serving plate.
15.  Cut any additional ingredients such as eggs, gizzards or bean curd puff and transfer them to the same serving plate as the duck and pour some gravy over them and garnish. Goes well with the traditional garlic chilli vinegar dipping sauce.

## Vegetarian

### Kimchi

**Ingredients**

-  1 medium head (~ 1 kg) wombok (chinese cabbage)
-  1/4 cup salt
-  Water
-  1 tbsp grated garlic (5 to 6 cloves)
-  1 tsp grated ginger
-  1 tsp sugar
-  2 to 3 tbsp fish sauce
-  1 to 5 tbsp Korean red pepper flakes (gochugaru)
-  250 g daikon (white radish), peeled and cut into 2.5 cm strips
-  4 green onions cut into 2.5 cm strips

**Method**

1.  Cut the cabbage lengthwise into quarters and remove the cores. Cut each quarter crosswise into 5-cm-wide strips.
2.  Place the cabbage and salt in a large bowl. Mix until it softens, then add water to cover the cabbage. Put a plate on top and weigh it down. Let stand for 1 to 2 hours.
3.  Rinse the cabbage under cold water and drain in a colander for 15 to 20 minutes. Rinse and dry the bowl you used for salting, and set it aside to use in step 5.
4.  Make the paste: combine the garlic, ginger, sugar, and fish sauce in a small bowl and mix to form a smooth paste. Mix in the gochugaru, using 1 tbsp for mild and up to 5 tbsp for spicy.
5.  Squeeze any remaining water from the cabbage and return it to the bowl along with the radish, scallions, and seasoning paste.
6.  Mix paste with the vegetables until they are coated.
7.  Pack the kimchi into the jar, pressing down on it until the brine rises to cover the vegetables. Leave at least 2.5 cm at the top. Seal the jar with the lid.
8.  Let the jar stand at room temperature for 3 to 5 days.
9.  Check the kimchi daily, pressing down on the vegetables to keep them submerged under the brine and release the gases.
10.  When ready refrigerate.

\newpage

### Nikki's crunchy noodle salad

**Ingredients**

-  1/2 wombok (chinese cabbage), sliced thinly
-  1 pkt Chang's fried noodles
-  6 shallots, sliced (optional)
-  1 cup toasted almond slivers (fuck almonds)
-  Dressing
    +  1/4 cup white vinegar
    +  1/4 cup sugar (if you don't have white sugar, substitute with brown sugar - reduce amount)
    +  1 tbsp soy sauce (reduce amount)
    +  2 tsps sesame oil (optional)
    +  1/2 cup olive oil (reduce to however oily you want to it to be)

**Method**

1.  Combine all of the dressing ingredients and stir until the sugar has dissolved. Taste to see if that's the tartness you like or else, add a bit more vinegar.
2.  In a salad bowl, combine the cabbage, almonds and shallots.
3.  Pour cooled dressing over and toss to coat.
4.  Just before serving, toss through the fried noodles

\newpage

### Yauhjagwai (Youtiao in mando)

<>
