# Desserts {-}

## Baking

### Aunty Gina's Apple Slice

**Ingredients**

-  500 g plain flour
-  200 g butter
-  2 eggs
-  1 egg yolk
-  150 g caster sugar
-  5-6 tbsp sour cream
-  5 tsp baking powder
-  1 kg granny smith apples (stew)
-  Sugar & cinnamon for apples

**Method**

1.  Sift flour and baking powder
2.  Soften butter and work into flour
3.  Add eggs, yolk, and cream then work into a dough
4.  Divide pastry into two and roll to suit baking tray
5.  Bake for 20 min or until golden
6.  Peel apples, mix with sugar and cinnamon then spread on top of pastry
7.  Roll second pastry on top, prick holes and bake on medium heat for approximately 30 mins.

\newpage

### Fruit crumble

**Ingredients**

-  425g drained canned fruit (or stewed apples)
-  0.5 cup plain flour
-  0.5 cup rolled oats
-  0.25 cup brown sugar
-  0.5 tsp cinnamon (optional)
-  3 tbsp melted butter

**Method**

1.  Preheat oven to 180°C.
2.  Mix dry ingredients together
3.  Add melted butter to the dry mixture and mix well
4.  Spoon fruit into a 1 L ovenproof dish then top with the crumble mixture
5.  Bake 25 to 30 mins

### Masa's chocolate terrine (from Tetsuya)

**Ingredients**

-  Part $A$
    +  2 kg butter
    +  1.8 kg chocolate (54% cocao)
-  Part *B*
    +  1.4 kg sugar
    +  40 eggs
-  Part *C*
    +  180g flour

**Method**

1.  Put *A* into bowl over hot/steaming water and melt.
2.  Mix *B* well
3.  Put *B* into *A* and mix well
4.  Add *C* into mixture and mix well
5.  Bake in oven at 85°C for 40 min with hot water

\newpage

### Pandan chiffon cake

**Ingredients**

-  Part $A$
    +  4 egg yolks
    +  70 g caster sugar (*note* 4 tbsp = 60g)
    +  0.25 tsp salt
-  Part *B*
    +  85 mL corn oil ($\frac{1}{3}$ cup = 80 mL)
    +  115 mL pandan juice
-  Part *C*
    +  150 g cake flour (1 cup = 155 g)
    +  1 tsp baking powder
-  Part *D*
    +  4 egg whites
    +  70 g caster sugar
    +  0.5 tsp tartar

**Method**

1.  Heat oven 170-180°C
2.  Sift *C* twice, set aside
3.  Cream *A* until sugar is dissolved. Add *B* in the order listed. Mix well after each addition.
4.  Add sifted flour and mix well
5.  Beat whiter until frothy, add tartar then beat until soft peaks. Add sugar then beat until stiff peaks.
6.  Fold $\frac{1}{2}$ egg white mixture into yolk mixture.
7.  Pour yolk mixture into white mixture gently
8.  Pour into pan (donut shaped) and bang once to release bubbles. Bake for 40-45 minutes.

\newpage

### 3 Ingredient cheesecake

<find recipe>

## Cold

### Mango pudding

**Ingredients**

-  3 large mangoes
-  1.5 tbsp gelatin
-  0.5 cup cold water
-  0.5 cup hot boiling water
-  $\frac{3}{4}$ cup sugar
-  3/4 cup evaporeated milk

**Method**

1.  Puree mangoes in a food processor.
2.  Soften gelatin in cold water, then add hot water and mix until dissolved. Set aside to cool, then combine with mango puree.
3.  Stir sugar and evaporated milk until sugar dissolves. Add mango mixture.
4.  Pour into a serving bowl and leave overnight.

### Tiramisu

**Ingredients**

-  250 g mascarpone
-  1 tsp vanilla
-  3 tbsp tia maria/marsala
-  150 mL strong coffee - cooled to room temperature
-  120 mL cream
-  4 tbsp icing sugar
-  16 savoiardi biscuits

**Method**

1.  Whisk mascarpone + vanilla + 50 mL coffee.
2.  Whisk cream and icing sugar until smooth, then fold into mascarpone.
3.  Pour remaining coffee into a bowl. Dip biscuits so they absorb the coffee then line the tin with biscuits.
4.  Layer cream mixture, then biscuits, then cream mixture.

## Traditional CNY

### Kuih Loyang (Honeycomb Cookies) (yields 40-50pcs)

**Ingredients**

-  400 ml coconut milk
-  200 gram all-purpose flour
-  200 gram rice flour
-  2 large eggs
-  170 gram sugar
-  200ml water
-  1/2 tsp salt
-  Oil for deep frying (e.g. vegetable oil)

**Method**

1.  Add coconut milk, eggs, sugar, water and salt in a mixing bowl and mix until well combined and all sugar are dissolved.
2.  Sift and all all-purpose flour and rice flour into the mixture. Whisk until well combined with no lumps. If is too thick, add one tablespoon of water at a time until the mixture resembling of a pancake batter.
3.  Heat up oil in a wok/saucepan on medium heat. Tips: dip a wooden chopstick into the hot oil, if the chopstick is bubbling up, it is ready.
4.  Preheat brass moulds in the hot oil, about 2-3 minutes. (The moulds have to be hot enough for batter to cling on them)
5.  CAUTIOUS: Dip hot mould into batter for 10 seconds. Make sure batter coats only the bottom and sides of mould, never over the top.
6.  Slowly lift it up and dip mould back in hot oil. Shake to release from mould and fry until golden brown on both sides.
7.  Take it out from hot oil, and let it cool over paper towel to soak up all the oil.
8.  Repeat until all batter is used up. Store in air-tight containers.

\newpage

### Kuih bingka ubi (Cassava cake)

**Ingredients**

-  500g cassava
-  1 cup sugar
-  1 cup coconut milk (santan)
-  125g butter – reduce to 50g
-  2 eggs
-  0.25 tsp salt
-  1.5 tbsp corn flour

**Method**

1.  Mix ingredients into a mixing bowl, then microwave at 1 minute intervals until thick.
2.  Bake at 190°C for 35 minutes

*Note: If doubling the recipe, use 2 pans*
